removed pygame.mixer.set_endevent(type) for it causes this error
  File "/home/pi/home/services/musicPlayer/musicplayer.py", line 145, in stop
    pygame.mixer.set_endevent(type)
AttributeError: module 'pygame.mixer' has no attribute 'set_endevent'